# Generated by Django 3.0.6 on 2020-05-26 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_question_choice_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choice_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='publish_date',
        ),
    ]
